begin;

create extension if not exists pgcrypto;

create or replace function public.set_current_timestamp_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table if not exists public.profiles (
  auth_user_id uuid primary key references auth.users(id) on delete cascade,
  username text not null,
  username_normalized text not null unique,
  email text not null,
  email_normalized text not null unique,
  role text not null default 'user' check (role in ('user', 'admin')),
  country text not null default 'unknown',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (char_length(username) between 3 and 40),
  check (username ~ '^[A-Za-z0-9_-]+$')
);

create index if not exists profiles_role_idx
  on public.profiles (role);

create index if not exists profiles_country_idx
  on public.profiles (country);

drop trigger if exists set_profiles_updated_at on public.profiles;
create trigger set_profiles_updated_at
before update on public.profiles
for each row
execute function public.set_current_timestamp_updated_at();

create table if not exists public.quiz_questions (
  id bigint generated by default as identity primary key,
  category text,
  question_en text,
  question_no text,
  answers_en text[] not null default '{}',
  answers_no text[] not null default '{}'
);

create index if not exists idx_quiz_questions_category_id
  on public.quiz_questions (category, id);

create index if not exists idx_quiz_questions_id_category
  on public.quiz_questions (id, category);

create index if not exists idx_quiz_questions_category_not_empty
  on public.quiz_questions (category)
  where category is not null and trim(category) <> '';

create table if not exists public.user_answers (
  user_id uuid not null references auth.users(id) on delete cascade,
  question_id bigint not null references public.quiz_questions(id) on delete cascade,
  is_correct boolean not null default false,
  primary key (user_id, question_id)
);

create index if not exists idx_user_answers_user_question_correct
  on public.user_answers (user_id, question_id, is_correct);

create index if not exists idx_user_answers_question_user
  on public.user_answers (question_id, user_id);

create table if not exists public.quiz_guest_progress (
  token text primary key,
  solved_question_ids integer[] not null default '{}',
  expires_at timestamptz not null,
  updated_at timestamptz not null default now()
);

drop trigger if exists set_quiz_guest_progress_updated_at on public.quiz_guest_progress;
create trigger set_quiz_guest_progress_updated_at
before update on public.quiz_guest_progress
for each row
execute function public.set_current_timestamp_updated_at();

create index if not exists quiz_guest_progress_expires_at_idx
  on public.quiz_guest_progress (expires_at);

create table if not exists public.quiz_rate_limits (
  scope text not null,
  client_ip text not null,
  window_bucket bigint not null,
  window_count integer not null,
  burst_bucket bigint,
  burst_count integer not null default 0,
  updated_at timestamptz not null default now(),
  primary key (scope, client_ip)
);

drop trigger if exists set_quiz_rate_limits_updated_at on public.quiz_rate_limits;
create trigger set_quiz_rate_limits_updated_at
before update on public.quiz_rate_limits
for each row
execute function public.set_current_timestamp_updated_at();

create index if not exists quiz_rate_limits_updated_at_idx
  on public.quiz_rate_limits (updated_at);

commit;
