begin;

create extension if not exists pgcrypto;

create table if not exists public.quiz_questions (
  id bigint generated by default as identity primary key,
  category text,
  question_en text,
  question_no text,
  answers_en text[] not null default '{}',
  answers_no text[] not null default '{}'
);

create index if not exists idx_quiz_questions_category_id
  on public.quiz_questions (category, id);

create index if not exists idx_quiz_questions_id_category
  on public.quiz_questions (id, category);

create index if not exists idx_quiz_questions_category_not_empty
  on public.quiz_questions (category)
  where category is not null and trim(category) <> '';

create table if not exists public.user_answers (
  user_id uuid not null references auth.users(id) on delete cascade,
  question_id bigint not null references public.quiz_questions(id) on delete cascade,
  is_correct boolean not null default false,
  primary key (user_id, question_id)
);

create index if not exists idx_user_answers_user_question_correct
  on public.user_answers (user_id, question_id, is_correct);

create index if not exists idx_user_answers_question_user
  on public.user_answers (question_id, user_id);

create table if not exists public.quiz_guest_progress (
  token text primary key,
  solved_question_ids integer[] not null default '{}',
  expires_at timestamptz not null,
  updated_at timestamptz not null default now()
);

create index if not exists quiz_guest_progress_expires_at_idx
  on public.quiz_guest_progress (expires_at);

create table if not exists public.quiz_rate_limits (
  scope text not null,
  client_ip text not null,
  window_bucket bigint not null,
  window_count integer not null,
  burst_bucket bigint,
  burst_count integer not null default 0,
  updated_at timestamptz not null default now(),
  primary key (scope, client_ip)
);

create index if not exists quiz_rate_limits_updated_at_idx
  on public.quiz_rate_limits (updated_at);

commit;
